DROP SEQUENCE SQ_TAREFA;
DROP TABLE TB_TAREFA;

CREATE TABLE TB_TAREFA (
	ID NUMBER NOT NULL PRIMARY KEY,
	DESCRICAO VARCHAR2(100) NOT NULL,
	FEITA NUMBER(1) DEFAULT 0,
	DATA_LIMITE DATE NOT NULL
);

CREATE SEQUENCE SQ_TAREFA INCREMENT BY 1 START WITH 1 NOCYCLE ORDER;

INSERT INTO TB_TAREFA(ID, DESCRICAO, DATA_LIMITE) VALUES (SQ_TAREFA.NEXTVAL, 'Fazer compras no mercado', TO_DATE('20/08/2020', 'dd/mm/yyyy'));

SELECT * FROM TB_TAREFA;